### ISSUE TITLE
"UnboundLocalError" when trying to get a previously initialized list

### ISSUE THREAD

**Issue by magicnum** [fwkz/riposte#22]
Following code 
```
from riposte import Riposte

mainrepl = Riposte(prompt="repl:~$ ")
DATA = []
@mainrepl.command("add")
def add(x: str):
	DATA += x
@mainrepl.command("get")
def get():
	mainrepl.success(DATA)
mainrepl.run()
```
Gives me
```
$python3 riposte_test.py
repl:~$ add foo
Traceback (most recent call last):
  File "riposte_test.py", line 15, in <module>
    mainrepl.run()
  File "/home/user/.local/lib/python3.7/site-packages/riposte/riposte.py", line 241, in run
    self._process()
  File "/home/user/.local/lib/python3.7/site-packages/riposte/riposte.py", line 228, in _process
    self._get_command(command_name).execute(*args)
  File "/home/user/.local/lib/python3.7/site-packages/riposte/command.py", line 106, in execute
    return self._func(*self._apply_guides(self._bind_arguments(*args)))
  File "riposte_test.py", line 9, in add
    DATA += x
UnboundLocalError: local variable 'DATA' referenced before assignment
```

Any class methods (for example, “assign” to a list) works fine.
Am I missing something? I can't find answer in docs.

```
$python3 -V
Python 3.7.3rc1
```

**Comment by fwkz** [comment]
This is normal Python's behavior and not specific to the _Riposte_ itself. Please make sure to read  about `global`. Few materials that might help you:
- https://docs.python.org/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python
- https://stackoverflow.com/questions/423379/using-global-variables-in-a-function
